name: release
on:
  workflow_run:
    workflows: ["lint,test"]
    types:
      - completed
  push:
    tags: ["v*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN}}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: build,publish
        run : uv build && uv publish
